name: medinet_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  shared_preferences:
  get: ^4.6.5


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.9.0
  easy_sidemenu: ^0.4.1
  cloud_firestore: ^4.4.5
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
